// Code generated by MockGen. DO NOT EDIT.
// Source: ownership.go
//
// Generated by this command:
//
//	mockgen -package ownership -source ownership.go -destination ownership_mock.go
//

// Package ownership is a generated GoMock package.
package ownership

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHistoryShardWatcher is a mock of HistoryShardWatcher interface.
type MockHistoryShardWatcher struct {
	ctrl     *gomock.Controller
	recorder *MockHistoryShardWatcherMockRecorder
	isgomock struct{}
}

// MockHistoryShardWatcherMockRecorder is the mock recorder for MockHistoryShardWatcher.
type MockHistoryShardWatcherMockRecorder struct {
	mock *MockHistoryShardWatcher
}

// NewMockHistoryShardWatcher creates a new mock instance.
func NewMockHistoryShardWatcher(ctrl *gomock.Controller) *MockHistoryShardWatcher {
	mock := &MockHistoryShardWatcher{ctrl: ctrl}
	mock.recorder = &MockHistoryShardWatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHistoryShardWatcher) EXPECT() *MockHistoryShardWatcherMockRecorder {
	return m.recorder
}

// AcquireNotifyChannel mocks base method.
func (m *MockHistoryShardWatcher) AcquireNotifyChannel() (chan struct{}, func()) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcquireNotifyChannel")
	ret0, _ := ret[0].(chan struct{})
	ret1, _ := ret[1].(func())
	return ret0, ret1
}

// AcquireNotifyChannel indicates an expected call of AcquireNotifyChannel.
func (mr *MockHistoryShardWatcherMockRecorder) AcquireNotifyChannel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcquireNotifyChannel", reflect.TypeOf((*MockHistoryShardWatcher)(nil).AcquireNotifyChannel))
}

// Owners mocks base method.
func (m *MockHistoryShardWatcher) Owners() []Address {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Owners")
	ret0, _ := ret[0].([]Address)
	return ret0
}

// Owners indicates an expected call of Owners.
func (mr *MockHistoryShardWatcherMockRecorder) Owners() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Owners", reflect.TypeOf((*MockHistoryShardWatcher)(nil).Owners))
}

// OwnershipStatus mocks base method.
func (m *MockHistoryShardWatcher) OwnershipStatus(shardID int32) (Status, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OwnershipStatus", shardID)
	ret0, _ := ret[0].(Status)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OwnershipStatus indicates an expected call of OwnershipStatus.
func (mr *MockHistoryShardWatcherMockRecorder) OwnershipStatus(shardID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OwnershipStatus", reflect.TypeOf((*MockHistoryShardWatcher)(nil).OwnershipStatus), shardID)
}

// MockHistoryShardOwner is a mock of HistoryShardOwner interface.
type MockHistoryShardOwner struct {
	ctrl     *gomock.Controller
	recorder *MockHistoryShardOwnerMockRecorder
	isgomock struct{}
}

// MockHistoryShardOwnerMockRecorder is the mock recorder for MockHistoryShardOwner.
type MockHistoryShardOwnerMockRecorder struct {
	mock *MockHistoryShardOwner
}

// NewMockHistoryShardOwner creates a new mock instance.
func NewMockHistoryShardOwner(ctrl *gomock.Controller) *MockHistoryShardOwner {
	mock := &MockHistoryShardOwner{ctrl: ctrl}
	mock.recorder = &MockHistoryShardOwnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHistoryShardOwner) EXPECT() *MockHistoryShardOwnerMockRecorder {
	return m.recorder
}

// ReportAccepting mocks base method.
func (m *MockHistoryShardOwner) ReportAccepting() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ReportAccepting")
}

// ReportAccepting indicates an expected call of ReportAccepting.
func (mr *MockHistoryShardOwnerMockRecorder) ReportAccepting() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportAccepting", reflect.TypeOf((*MockHistoryShardOwner)(nil).ReportAccepting))
}

// ReportShardOwnership mocks base method.
func (m *MockHistoryShardOwner) ReportShardOwnership(shardID int32, arg1 ShardOwnershipStatus) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ReportShardOwnership", shardID, arg1)
}

// ReportShardOwnership indicates an expected call of ReportShardOwnership.
func (mr *MockHistoryShardOwnerMockRecorder) ReportShardOwnership(shardID, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportShardOwnership", reflect.TypeOf((*MockHistoryShardOwner)(nil).ReportShardOwnership), shardID, arg1)
}

// ReportStopping mocks base method.
func (m *MockHistoryShardOwner) ReportStopping() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ReportStopping")
}

// ReportStopping indicates an expected call of ReportStopping.
func (mr *MockHistoryShardOwnerMockRecorder) ReportStopping() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportStopping", reflect.TypeOf((*MockHistoryShardOwner)(nil).ReportStopping))
}
